name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: octokit/request-action@v2.x
        id: get_required_status_checks
        with:
          route: GET /repos/:repository/branches/:branch/protection/required_status_checks/contexts
          repository: ${{ github.repository }}
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.PROTECTED_PAT }}
      # - name: echo GET
      #   # run: "echo required status checks: ${{ steps.get_required_status_checks.outputs.data }}"
      #   run: "echo required status checks: ${{ fromJson(steps.get_required_status_checks.outputs.data) }}"
      - uses: octokit/request-action@v2.x
        id: put_required_status_checks_off
        with:
          route: PUT /repos/:repository/branches/:branch/protection/required_status_checks/contexts
          repository: ${{ github.repository }}
          branch: main
          data: "[]"
        env:
          GITHUB_TOKEN: ${{ secrets.PROTECTED_PAT }}
      # - name: echo OFF
      #   run: "echo required status checks: ${{ steps.put_required_status_checks_off.outputs.data }}"
      - name: commit
        run: |
          echo $(uuidgen) > test.txt
          git config --global user.name ${{ github.actor }}
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add test.txt
          git commit -m "Update test.txt"
          git push
      - uses: octokit/request-action@v2.x
        id: put_required_status_checks_on
        with:
          route: PUT /repos/:owner/:repo/branches/:branch/protection/required_status_checks/contexts
          mediaType: |
            previews:
              - antiope
          contexts: |
            ${{ steps.get_required_status_checks.outputs.data }}
        env:
          GITHUB_TOKEN: ${{ secrets.PROTECTED_PAT }}
      # - name: echo ON
      #   run: "echo required status checks: ${{ steps.put_required_status_checks_on.outputs.data }}"
