name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'testing...'
      - name: commit
        run: |
          echo $(uuidgen) > test.txt
          git config --global user.name ${{ github.actor }}
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add test.txt
          git commit -m "Update test.txt"
          git push
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
